uci add dhcp domain
uci set dhcp.@domain[-1].name='time.android.com'
uci set dhcp.@domain[-1].ip='203.107.6.88'
uci commit dhcp
cd /tmp
wget https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all//OpenClash_x86_update.run
wget https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/PassWall_x86_update.run
wget https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/SSR-Plus_x86_update.run
sh OpenClash_x86_update.run
sh PassWall_x86_update.run
sh SSR-Plus_x86_update.run
wget https://github.com/vernesong/OpenClash/releases/download/v0.45.141-beta/luci-app-openclash_0.45.141-beta_all.ipk
opkg install luci-app-openclash_0.45.141-beta_all.ipk



